Repository googleapis/nodejs-managed-identities, pull requests merged in 2021-02, with the labels that each got.

#10 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#9 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#15 chore: update copyrights, protos, and config
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  README.md
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/gapic_metadata.json
  src/v1/index.ts
  src/v1/managed_identities_service_client.ts
  src/v1beta1/gapic_metadata.json
  src/v1beta1/index.ts
  src/v1beta1/managed_identities_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_managed_identities_service_v1.ts
  test/gapic_managed_identities_service_v1beta1.ts
Labels: cla: yes, context: partial

#17 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full
