Repository googleapis/nodejs-managed-identities, pull requests merged in 2021-03, with the labels that each got.

#18 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: managedidentities, automerge, cla: yes, context: full

#19 chore: Remove titles in docstring.
  protos/google/cloud/managedidentities/v1/managed_identities_service.proto
  src/v1/managed_identities_service_client.ts
  synth.metadata
Labels: api: managedidentities, cla: yes, context: full

#20 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: managedidentities, cla: yes
